version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: "America/New_York"
    time: "06:00"
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: "America/New_York"
